// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatsRequest) Reset() {
	*x = GetEventStatsRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsRequest) ProtoMessage() {}

func (x *GetEventStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsRequest.ProtoReflect.Descriptor instead.
func (*GetEventStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventStatsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetEventStatsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetEventStatsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GetEventStatsRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

type EventStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TotalEvents   int64                  `protobuf:"varint,3,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,4,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStats) Reset() {
	*x = EventStats{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStats) ProtoMessage() {}

func (x *EventStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStats.ProtoReflect.Descriptor instead.
func (*EventStats) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *EventStats) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventStats) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventStats) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *EventStats) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *EventStats) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetEventStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*EventStats          `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatsResponse) Reset() {
	*x = GetEventStatsResponse{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsResponse) ProtoMessage() {}

func (x *GetEventStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsResponse.ProtoReflect.Descriptor instead.
func (*GetEventStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventStatsResponse) GetStats() []*EventStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetEventStatsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // количество событий
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityRequest) Reset() {
	*x = GetUserActivityRequest{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityRequest) ProtoMessage() {}

func (x *GetUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserActivityRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetUserActivityRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetUserActivityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *UserEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UserEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UserEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UserEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetUserActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Events        []*UserEvent           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	TotalEvents   int64                  `protobuf:"varint,3,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityResponse) Reset() {
	*x = GetUserActivityResponse{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityResponse) ProtoMessage() {}

func (x *GetUserActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityResponse.ProtoReflect.Descriptor instead.
func (*GetUserActivityResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserActivityResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserActivityResponse) GetEvents() []*UserEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetUserActivityResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type GetTopProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopProductsRequest) Reset() {
	*x = GetTopProductsRequest{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopProductsRequest) ProtoMessage() {}

func (x *GetTopProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopProductsRequest.ProtoReflect.Descriptor instead.
func (*GetTopProductsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopProductsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetTopProductsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetTopProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopProductsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ProductStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EventCount     int64                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	UniqueUsers    int64                  `protobuf:"varint,3,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	ConversionRate float64                `protobuf:"fixed64,4,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductStats) Reset() {
	*x = ProductStats{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStats) ProtoMessage() {}

func (x *ProductStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStats.ProtoReflect.Descriptor instead.
func (*ProductStats) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ProductStats) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductStats) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *ProductStats) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *ProductStats) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *ProductStats) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTopProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductStats        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopProductsResponse) Reset() {
	*x = GetTopProductsResponse{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopProductsResponse) ProtoMessage() {}

func (x *GetTopProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopProductsResponse.ProtoReflect.Descriptor instead.
func (*GetTopProductsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopProductsResponse) GetProducts() []*ProductStats {
	if x != nil {
		return x.Products
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Dependencies  map[string]string      `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetDependencies() map[string]string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\x14GetEventStatsRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\"\xa9\x02\n" +
	"\n" +
	"EventStats\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\ftotal_events\x18\x03 \x01(\x03R\vtotalEvents\x12!\n" +
	"\funique_users\x18\x04 \x01(\x03R\vuniqueUsers\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.analytics.EventStats.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x15GetEventStatsResponse\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.analytics.EventStatsR\x05stats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xa3\x01\n" +
	"\x16GetUserActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9b\x02\n" +
	"\tUserEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".analytics.UserEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x17GetUserActivityResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x06events\x18\x02 \x03(\v2\x14.analytics.UserEventR\x06events\x12!\n" +
	"\ftotal_events\x18\x03 \x01(\x03R\vtotalEvents\"\xa8\x01\n" +
	"\x15GetTopProductsRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\"\x9a\x02\n" +
	"\fProductStats\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x03R\n" +
	"eventCount\x12!\n" +
	"\funique_users\x18\x03 \x01(\x03R\vuniqueUsers\x12'\n" +
	"\x0fconversion_rate\x18\x04 \x01(\x01R\x0econversionRate\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.analytics.ProductStats.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x16GetTopProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.analytics.ProductStatsR\bproducts\"\x14\n" +
	"\x12HealthCheckRequest\"\xde\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12T\n" +
	"\fdependencies\x18\x03 \x03(\v20.analytics.HealthCheckResponse.DependenciesEntryR\fdependencies\x1a?\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe1\x02\n" +
	"\fQueryService\x12R\n" +
	"\rGetEventStats\x12\x1f.analytics.GetEventStatsRequest\x1a .analytics.GetEventStatsResponse\x12X\n" +
	"\x0fGetUserActivity\x12!.analytics.GetUserActivityRequest\x1a\".analytics.GetUserActivityResponse\x12U\n" +
	"\x0eGetTopProducts\x12 .analytics.GetTopProductsRequest\x1a!.analytics.GetTopProductsResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.analytics.HealthCheckRequest\x1a\x1e.analytics.HealthCheckResponseB;Z9github.com/Wuchinator/realtime-analytics/pkg/pb/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_analytics_proto_goTypes = []any{
	(*GetEventStatsRequest)(nil),    // 0: analytics.GetEventStatsRequest
	(*EventStats)(nil),              // 1: analytics.EventStats
	(*GetEventStatsResponse)(nil),   // 2: analytics.GetEventStatsResponse
	(*GetUserActivityRequest)(nil),  // 3: analytics.GetUserActivityRequest
	(*UserEvent)(nil),               // 4: analytics.UserEvent
	(*GetUserActivityResponse)(nil), // 5: analytics.GetUserActivityResponse
	(*GetTopProductsRequest)(nil),   // 6: analytics.GetTopProductsRequest
	(*ProductStats)(nil),            // 7: analytics.ProductStats
	(*GetTopProductsResponse)(nil),  // 8: analytics.GetTopProductsResponse
	(*HealthCheckRequest)(nil),      // 9: analytics.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 10: analytics.HealthCheckResponse
	nil,                             // 11: analytics.EventStats.MetadataEntry
	nil,                             // 12: analytics.UserEvent.MetadataEntry
	nil,                             // 13: analytics.ProductStats.MetadataEntry
	nil,                             // 14: analytics.HealthCheckResponse.DependenciesEntry
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_analytics_proto_depIdxs = []int32{
	15, // 0: analytics.GetEventStatsRequest.from:type_name -> google.protobuf.Timestamp
	15, // 1: analytics.GetEventStatsRequest.to:type_name -> google.protobuf.Timestamp
	15, // 2: analytics.EventStats.timestamp:type_name -> google.protobuf.Timestamp
	11, // 3: analytics.EventStats.metadata:type_name -> analytics.EventStats.MetadataEntry
	1,  // 4: analytics.GetEventStatsResponse.stats:type_name -> analytics.EventStats
	15, // 5: analytics.GetUserActivityRequest.from:type_name -> google.protobuf.Timestamp
	15, // 6: analytics.GetUserActivityRequest.to:type_name -> google.protobuf.Timestamp
	15, // 7: analytics.UserEvent.timestamp:type_name -> google.protobuf.Timestamp
	12, // 8: analytics.UserEvent.metadata:type_name -> analytics.UserEvent.MetadataEntry
	4,  // 9: analytics.GetUserActivityResponse.events:type_name -> analytics.UserEvent
	15, // 10: analytics.GetTopProductsRequest.from:type_name -> google.protobuf.Timestamp
	15, // 11: analytics.GetTopProductsRequest.to:type_name -> google.protobuf.Timestamp
	13, // 12: analytics.ProductStats.metadata:type_name -> analytics.ProductStats.MetadataEntry
	7,  // 13: analytics.GetTopProductsResponse.products:type_name -> analytics.ProductStats
	14, // 14: analytics.HealthCheckResponse.dependencies:type_name -> analytics.HealthCheckResponse.DependenciesEntry
	0,  // 15: analytics.QueryService.GetEventStats:input_type -> analytics.GetEventStatsRequest
	3,  // 16: analytics.QueryService.GetUserActivity:input_type -> analytics.GetUserActivityRequest
	6,  // 17: analytics.QueryService.GetTopProducts:input_type -> analytics.GetTopProductsRequest
	9,  // 18: analytics.QueryService.HealthCheck:input_type -> analytics.HealthCheckRequest
	2,  // 19: analytics.QueryService.GetEventStats:output_type -> analytics.GetEventStatsResponse
	5,  // 20: analytics.QueryService.GetUserActivity:output_type -> analytics.GetUserActivityResponse
	8,  // 21: analytics.QueryService.GetTopProducts:output_type -> analytics.GetTopProductsResponse
	10, // 22: analytics.QueryService.HealthCheck:output_type -> analytics.HealthCheckResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
